modimport("combat_bosses")

local um = GLOBAL.KnownModIndex:IsModEnabled("workshop-2039181790")
local TUNING = GLOBAL.TUNING

if GetModConfigData("lowerbosshp") then
    TUNING.CRABKING_HEALTH = TUNING.CRABKING_HEALTH * 0.66
    TUNING.CRABKING_HEALTH_BONUS = TUNING.CRABKING_HEALTH * 0.66

    if TUNING.WATHOM == nil then
        TUNING.BEEQUEEN_HEALTH = TUNING.BEEQUEEN_HEALTH * 0.75
        --GLOBAL.TUNING.TOADSTOOL_HEALTH = TUNING.TOADSTOOL_HEALTH/2
    else --to override the configs
        TUNING.WATHOM.BEEQUEEN_HEALTH = TUNING.BEEQUEEN_HEALTH * 0.75
        TUNING.WATHOM.TWIN1_HEALTH = TUNING.TWIN1_HEALTH * 0.66
        TUNING.WATHOM.TWIN2_HEALTH = TUNING.TWIN2_HEALTH * 0.66
        --TUNING.WATHOM.TOADSTOOL_HEALTH = TUNING.TOADSTOOL_HEALTH/2
    end

    TUNING.STALKER_ATRIUM_HEALTH = TUNING.STALKER_ATRIUM_HEALTH * 0.75
    TUNING.STALKER_ATRIUM_PHASE2_HEALTH = TUNING.STALKER_ATRIUM_PHASE2_HEALTH * 0.75

    TUNING.DRAGONFLY_HEALTH = TUNING.DRAGONFLY_HEALTH * 0.75

    TUNING.TWIN1_HEALTH = TUNING.TWIN1_HEALTH * 0.66
    TUNING.TWIN2_HEALTH = TUNING.TWIN2_HEALTH * 0.66
end